common:
    seed: 0
    trainer: GTAMixTrainer
    dataset: 
        arch: get_mix_GTA_dataset
        name: CommonDataset
    model:
        arch: hf_net
        kwargs:
            channel_list: [3,30,120]
            n_block: 2

    augmentation:
      type: Common_aug
      kwargs:
        input_size_h: 512
        input_size_w: 512
        scale_down: 0.7

    workers: 8
    batch_size: 1

    lr_scheduler:
        type: COSINE
        T_max: 100000
        eta_min: 0.0000001
        base_lr: 0.0001
        max_iter: 100000
        warmup_steps: 0
        warmup_lr: 0.0001

    optimizer:
        type: Adam
        kwargs:
            weight_decay: 0.0005

    criterion:
        type: vgg_loss
        kwargs:
            k: 0.9
            vgg_path: ../model/losses/vgg_model/vgg_normalised.pth
        
    save_freq: 100
    print_freq: 100

    background_config:
        backgrounds: /mnt/lustre/rws3/classification_data/new_data/backgrounds/
        prob: 1.0
        extend_ratio: 0.25
        cut_ratio: 0.1

    read_from: mc

    source_root: 
    target_root: 