common:
    seed: 0
    trainer: DehazeTrainer
    dataset: 
        arch: get_COCO2Wiki_dataset
        name: DehazeDataset
    model:
        arch: hf_net
        kwargs:
            channel_list: [3,30,120,360]
            n_block: 3

    augmentation:
      type: eval_aug
      kwargs:
        input_size_h: 512
        input_size_w: 512

    workers: 8
    batch_size: 1

    lr_scheduler:
        type: COSINE
        T_max: 300000
        eta_min: 0.0000000
        base_lr: 0.0001
        max_iter: 300000
        warmup_steps: 0
        warmup_lr: 0.0001


    optimizer:
        type: Adam
        kwargs:
            weight_decay: 0.00000

    criterion:
        type: dehaze_loss
        kwargs:
            k: 1.0
            vgg_path: ../model/losses/vgg_model/vgg_normalised.pth
            weight_content: 0.0
            weight_style: 1.0
        
    save_freq: 100
    print_freq: 100

    # source_root: /mnt/lustre/fanweichen2/RESEARCH/ROBI/Chrome_screw/croped/train/gen_file.txt
    # target_root: /mnt/lustre/fanweichen2/RESEARCH/ROBI/Chrome_screw/croped/train/img_file.txt

    source_root: /mnt/lustre/fanweichen2/RESEARCH/ROBI/Eye_bolt/croped/val/gen_file.txt
    target_root: /mnt/lustre/fanweichen2/RESEARCH/ROBI/Eye_bolt/croped/val/img_file.txt