common:
    seed: 0
    trainer: GlowTrainer
    dataset: 
        arch: get_COCO2Wiki_dataset
        name: DeDataset
    model:
        arch: glow_net_de
        kwargs:
            channel_list: [3,30,120]
            n_block: 3

    augmentation:
      type: De_aug
      kwargs:
        input_size_h: 28
        input_size_w: 28
        scale_down: 0.5

    workers: 8
    batch_size: 16
    n_bins: 5

    lr_scheduler:
        type: COSINE
        T_max: 5000000
        eta_min: 0.0000000
        base_lr: 0.00001
        max_iter: 5000000
        warmup_steps: 0
        warmup_lr: 0.00001
    optimizer:
        type: AdamW
        kwargs:
            weight_decay: 0.01

    criterion:
        type: vgg_loss
        kwargs:
            k: 1.0
            vgg_path: ../model/losses/vgg_model/vgg_normalised.pth
        
    save_freq: 100
    print_freq: 100


    source_root: /mnt/lustre/fanweichen2/RESEARCH/I2I/data/MNIST/train.txt
    target_root: /mnt/lustre/fanweichen2/RESEARCH/I2I/data/MNIST/train.txt